config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      delete 'dissociate_seller', to: 'devices#dissociate_seller'
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'

  resources :api_manager

  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  


  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true



    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/models/device_seller.rb
class DeviceSeller < ApplicationRecord
  belongs_to :device
  belongs_to :seller
end

app/models/dose_price.rb
class DosePrice < ApplicationRecord
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_and_belongs_to_many :devices
end

app/models/sms_log.rb
class SmsLog < ApplicationRecord
   
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_one :sms_configuration

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { admin: 'admin', user: 'user'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sms_messages_controller.rb
require 'httparty'
require 'twilio-ruby'

class SmsMessagesController < ApplicationController
  before_action :set_sms_message, only: %i[ show edit update destroy ]

  # GET /sms_messages or /sms_messages.json
  def index
    #@sms_messages = SmsMessage.all
    @sms_logs = SmsLog.all
    @sms_messages = SmsMessage.all
    @last_sms_message = @sms_messages.last
    #@sms_messages = SmsMessage.last
  end

  # GET /sms_messages/1 or /sms_messages/1.json
  def show
  end

  # GET /sms_messages/new
  def new
    @sms_message = SmsMessage.new
    #@sms_template = SmsTemplate.new
  end

  # GET /sms_messages/1/edit
  def edit
    #@sms_message = SmsMessage.find(params[:id])
  end


  # POST /sms_messages or /sms_messages.json
  def create
    @sms_message = SmsMessage.new(sms_message_params)

    respond_to do |format|
      if @sms_message.save
        format.html { redirect_to sms_messages_path(@sms_message), notice: "Sms message was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sms_messages/1 or /sms_messages/1.json
  def update
    respond_to do |format|
      if @sms_message.update(sms_message_params)
        format.html { redirect_to sms_messages_path(@sms_message), notice: "Sms message was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def logs_message
    @sms_logs = SmsLog.all
  end

  # DELETE /sms_messages/1 or /sms_messages/1.json
  def destroy
    @sms_message.destroy

    respond_to do |format|
      format.html { redirect_to sms_messages_url, notice: "Sms message was successfully destroyed." }
    end
  end

  def send_sms_twilio
    account_sid = 'ACcbd199f02e7c1e843cd953a16ac1e714'
    auth_token = '81ad8e628f8487a68a5d3b2131e149f9'
    client = Twilio::REST::Client.new(account_sid, auth_token)

    phone_numbers = fetch_phone_numbers_from_api
    if params[:cont].to_i == 80 && phone_numbers.any?
      phone_number = phone_numbers.first['phone']
      send_sms_to_phone(client, phone_number)
      #redirect_to sms_messages_path, notice: "SMS enviado automaticamente!"
      return
    else
      render json: { message: 'SMS nao enviado automaticamente.' }
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sms_message
      @sms_message = SmsMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sms_message_params
      params.require(:sms_message).permit(:smsbody)
    end

    def fetch_phone_numbers_from_api
      api_url = 'https://dispenser-smart-api-9ae096adb72b.herokuapp.com/esp8266s'
      headers = {
        'Authorization' => 'Bearer YOUR_API_TOKEN' # Se sua API necessita de um token de autenticação, adicione-o aqui
      }
      
      response = HTTParty.get(api_url, headers: headers)
      if response.success?
        response.parsed_response
      else
        []
      end
    end

    def send_sms_to_phone(client, phone_number)
      from = '15416128239' # Número de telefone fornecido pela Twilio
      puts "Conteúdo de @last_sms_message: #{@last_sms_message}"
      body = @last_sms_message = SmsMessage.last
      #body = @last_sms_message.smsbody # Corpo da mensagem SMS
      #body = "TESTE" # Corpo da mensagem SMS

      
      #to = '5561992488131' # Número de telefone do destinatário Luis RFID
      #to = '5561998058131'
      #to = '5561995762787' # Número de telefone do destinatário Caio
      #to = '5561993212899' #Caian
      #to = '5561991150833' #Ivanice
  
      message = client.messages.create(
        from: from,
        to: phone_number,
        body: body
      )
  
      # Salva o log da mensagem
      sms_log = SmsLog.create(
        from_number: message.from,
        to_number: message.to,
        body: message.body,
        sent_at: Time.now
      )
    rescue Twilio::REST::TwilioError => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_manager_helper.rb
module ApiManagerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devicelogs_helper.rb
module DevicelogsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/dose_prices_helper.rb
module DosePricesHelper
end

app/helpers/esp8266_helper.rb
module Esp8266Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/sms_messages/_form.html.erb
<%= form_with(model: sms_message) do |form| %>
  <% if sms_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sms_message.errors.count, "error") %> prohibited this sms_message from being saved:</h2>

      <ul>
        <% sms_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :smsbody, style: "display: block" %>
    <%= form.text_field :smsbody %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sms_messages/_sms_message.html.erb
<div id="<%= dom_id sms_message %>">
  <p>
    <strong>Smsbody:</strong>
    <%= sms_message.smsbody %>
  </p>

</div>

app/views/sms_messages/edit.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to user_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Configurações de Alerta</h3>
              </div>
              <div class="col-lg-9">
                <h1 class="mt-4">Editar Mensagem Padrão</h1>
                  <h2></h2>
                    <%= form_for @sms_message do |f| %>
                      <%= f.label :smsbody, "Mensagem:" %>
                      <%= f.text_area :smsbody, class: "form-control" %>
                      </br>
                      <%= f.submit "Atualizar", class: "btn btn-primary" %>
                      <%= link_to "Voltar", sms_messages_path, class: "btn btn-success" %>
                    <% end %>
              </div> 
              <!-- /top tiles -->
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

app/views/sms_messages/index.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to user_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Histórico de Mensagens</h3>
              </div>

              <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-9">
                  <h1 class="mt-4">Configurações de Alerta</h1>
                  <div class="container">
                    <!-- Exibe o formulário de criação ou edição da mensagem padrão -->
                    <% if @sms_messages.any? %>
                      <% last_sms_message = @sms_messages.last %>
                      <h2>Mensagem Padrão: <%= last_sms_message.smsbody %> </h2>
                      </br>
                    
                      <div class="d-flex justify-content-start">
                        <%= form_tag send_sms_twilio_path, method: :post, class: "d-inline" do %>
                          <%= hidden_field_tag :phone, '5561995762787' %> <!-- Número de telefone para disparo -->
                          <%= hidden_field_tag :cont, '80' %> <!-- Exemplo do campo "cont" igual a 80 -->
                          <%= submit_tag "Disparar SMS", class: "btn btn-success" %>
                        <% end %>
            
                        <%= link_to "Editar", edit_sms_message_path(last_sms_message), class: "btn btn-primary mx-1" %>
                        <%= link_to "Histórico de Alertas", logs_message_path, class: "btn btn-warning" %>
                        <%= button_to "Apagar", sms_message_path(last_sms_message), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger mx-1" %>
                      </div>
                    <% else %>
                      <p>Nenhuma mensagem padrão criada.</p>
                      <%= link_to "Criar Mensagem Padrão", new_sms_message_path, class: "btn btn-success" %>
                    <% end %>
                    <!-- Botão de disparo manual do SMS -->
                  </div>
                </div>
              </div>
            </div>
            


          

                  </div>
                </div>
              <!-- /top tiles -->
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

app/views/sms_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sms_message %>

<div>
  <%= link_to "Edit this sms message", edit_sms_message_path(@sms_message) %> |
  <%= link_to "Back to sms messages", sms_messages_path %>

  <%= button_to "Destroy this sms message", @sms_message, method: :delete %>
</div>