config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      delete 'dissociate_seller', to: 'devices#dissociate_seller'
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'

  resources :api_manager

  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  


  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true



    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/models/device_seller.rb
class DeviceSeller < ApplicationRecord
  belongs_to :device
  belongs_to :seller
end

app/models/dose_price.rb
class DosePrice < ApplicationRecord
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_and_belongs_to_many :devices
end

app/models/sms_log.rb
class SmsLog < ApplicationRecord
   
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_one :sms_configuration

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { admin: 'admin', user: 'user'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: %i[show edit update destroy attach_devices save_attached_devices]

  # GET /sellers or /sellers.json
  def index
    @sellers = Seller.all
    @devices = Device.all
    #@devices = Device.includes(:seller)
  end

  def associate_device_seller
    @device = Device.find(params[:id])
    seller_id = params[:device][:seller_id]
    @seller = Seller.find(seller_id)

    if @device.update(seller_id: seller_id)
      redirect_to @device, notice: "Device associated with seller successfully!"
    else
      render :show, alert: "Error associating the device with the seller."
    end
  end


  def attach_devices
    @seller = Seller.find(params[:id])
    @devices = Device.all
  end

  def save_attached_devices
    @seller = Seller.find(params[:id])
    selected_device_ids = params[:seller][:device_ids]

    # Limpa as associações atuais com os devices
    @seller.devices.clear

    # Associa os dispositivos selecionados ao seller
    if selected_device_ids.present?
      selected_device_ids.each do |device_id|
        device = Device.find(device_id)
        @seller.devices << device
      end
    end

    redirect_to sellers_path, notice: 'Devices atrelados com sucesso!'
  end

  # GET /sellers/1 or /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers or /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully created." }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1 or /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully updated." }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1 or /sellers/1.json
  def destroy
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url, notice: "Seller was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def associate_device
    @seller = Seller.find(params[:seller_id])
    @device = Device.find(params[:device_id])

    if @device.sellers << @seller
      redirect_to devices_path, notice: 'Vendedor associado com sucesso!'
    else
      redirect_to devices_path, alert: 'Erro ao associar vendedor ao dispositivo.'
    end
  end

  private

    # Define o filtro para carregar o @seller com base no ID fornecido na URL
    def set_seller
      @seller = Seller.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to sellers_path, alert: 'Seller não encontrado.'
    end


    # Only allow a list of trusted parameters through.
    def seller_params
      params.require(:seller).permit(:id, :status, :nome, :cardRFID, :cargo, :contador, :email)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        @devices = current_user.devices
    end

  
    def show
        @user = User.find(params[:id])
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_manager_helper.rb
module ApiManagerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devicelogs_helper.rb
module DevicelogsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/dose_prices_helper.rb
module DosePricesHelper
end

app/helpers/esp8266_helper.rb
module Esp8266Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/sellers/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: seller, class: "form") do |form| %>
        <% if seller.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

            <ul>
              <% seller.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :status %>
          <%= form.text_field :status, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :nome %>
          <%= form.text_field :nome, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :cardRFID %>
          <%= form.text_field :cardRFID, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :cargo %>
          <%= form.text_field :cargo, class: "form-control" %>
        </div>

        <div class="form-group mb-4">
          <%= form.label :contador %>
          <%= form.number_field :contador, class: "form-control" %>
        </div>
        <div class="button-group">
          <div class="form-group d-inline-block">
            <%= form.submit "Cadastrar Usuário", class: "btn btn-primary" %>
          </div>
          <div class="form-group d-inline-block">
            <%= link_to "Voltar", sellers_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sellers/_seller.html.erb
<div id="<%= dom_id seller %>">
  <p>
    <strong>Status:</strong>
    <%= seller.status %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= seller.nome %>
  </p>

  <p>
    <strong>Cardrfid:</strong>
    <%= seller.cardRFID %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= seller.cargo %>
  </p>

  <p>
    <strong>Contador:</strong>
    <%= seller.contador %>
  </p>

  <p>
  <strong>Email:</strong>
  <%= seller.email %>
</p>

</div>

app/views/sellers/attach_devices.html.erb
<!-- app/views/sellers/attach_devices.html.erb -->
<h1>Atrelar Devices ao Seller</h1>
<%= form_with model: @seller, url: save_attached_devices_seller_path(@seller), method: :post do |f| %>
  <h2>Dispositivos Disponíveis</h2>
  <% @devices.each do |device| %>
    <%= check_box_tag "seller[device_ids][]", device.id, @seller.devices.include?(device) %>
    <%= device.nome %>
    <br>
  <% end %>

  <%= f.submit "Salvar" %>
<% end %>

app/views/sellers/edit.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to user_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Editar de Vendedores</h3>
              </div>
              <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                    <%= render "form", seller: @seller %>
                    </div>
                  </div>
                </div>
              <!-- /top tiles -->
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

app/views/sellers/index.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Gerenciamento de Vendedores</h3>
                <%= link_to "Atrelar Dispositivo", devices_in_use_seller_path, class: 'btn btn-success' %>
              </div>
              <% if current_user.admin? %>
              <% else %>
                <%= link_to "Novo vendedor", new_seller_path, class: "btn btn-success" %>
              <% end %>
            </div>
      
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-12">
                  <div class="table-responsive">
                    <table class="table table-responsive-sm">
                      <thead>
                        <tr>
                          <th>Status</th>
                          <th>Nome</th>
                          <th>Cartão RFID</th>
                          <th>Cargo</th>
                          <th>Doses</th>
                          <th>Email</th>
                          <th>Ver</th>
                          <th>Editar</th>
                          <th>Excluir</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @sellers.each do |seller| %>
                          <tr>
                            <td><%= seller.status %></td>
                            <td><%= seller.nome %></td>
                            <td><%= seller.cardRFID %></td>
                            <td><button type="button" class="btn btn-info"><%= seller.cargo %></button></td>
                            <td><%= seller.contador %></td>
                            <td><%= seller.email %></td>
                            <td>
                              <%= button_to seller_path(seller), method: :get, class: 'btn btn-primary' do %>
                                <i class="glyphicon glyphicon-search"></i>
                              <% end %>
                            </td>
      
                            <td>
                              <%= button_to edit_seller_path(seller), method: :get, class: 'btn btn-warning' do %>
                                <i class="glyphicon glyphicon-edit"></i>
                              <% end %>
                            </td>
      
                            <td>
                              <%= button_to seller_path(seller), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
                                <i class="glyphicon glyphicon-trash"></i>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

      
      
     

                  <!-- /top tiles -->
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

app/views/sellers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @seller %>

<div>
  <%= link_to "Edit this seller", edit_seller_path(@seller) %> |
  <%= link_to "Back to sellers", sellers_path %>

  <%= button_to "Destroy this seller", @seller, method: :delete %>
</div>