config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      delete 'dissociate_seller', to: 'devices#dissociate_seller'
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'

  resources :api_manager

  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  


  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true



    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/models/device_seller.rb
class DeviceSeller < ApplicationRecord
  belongs_to :device
  belongs_to :seller
end

app/models/dose_price.rb
class DosePrice < ApplicationRecord
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_and_belongs_to_many :devices
end

app/models/sms_log.rb
class SmsLog < ApplicationRecord
   
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_one :sms_configuration

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { admin: 'admin', user: 'user'}
end

app/controllers/administrador/users_controller.rb
class Administrador::UsersController < ApplicationController
    before_action :authenticate_admin! # Adicione um filtro para autenticar o administrador

  def index
    @users = User.where.not(id: current_user.id) # Exclui o próprio administrador da lista
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'Usuário atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to administrador_users_path, notice: 'Usuário excluído com sucesso.'
  end

  private

  def authenticate_admin!
    # Coloque aqui a lógica para verificar se o usuário atual é um administrador
    # Por exemplo, você pode ter um atributo "admin" no modelo User e verificar se ele é verdadeiro (true) aqui.
    # Além disso, verifique também se o usuário está logado para evitar acesso não autorizado.
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        @devices = current_user.devices
    end

  
    def show
        @user = User.find(params[:id])
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/administrador/users_helper.rb
module Administrador::UsersHelper
end

app/helpers/api_manager_helper.rb
module ApiManagerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devicelogs_helper.rb
module DevicelogsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/dose_prices_helper.rb
module DosePricesHelper
end

app/helpers/esp8266_helper.rb
module Esp8266Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/administrador/users/edit.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to user_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
    
        <!-- /top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Gerenciamento de Usuários</h3>
              </div>
              <div class="container">
                <div class="row justify-content-center">
                  <div class="col-md-8">
                    <%= form_for @user, url: administrador_users_path(@user), method: :patch do |f| %>
                        <div class="field">
                        <%= f.label :Email %><br />
                        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                        </div>
                    
                        <div class="field">
                        <%= f.label :Nome %><br />
                        <%= f.text_field :name, autocomplete: "name" %>
                        </div>
                    
                        <div class="field">
                        <%= f.label :Telefone %><br />
                        <%= f.text_field :phone, autocomplete: "phone" %>
                        </div>
                        </br>
                        <div class="actions">
                        <%= f.submit 'Salvar', class: 'btn btn-primary' %>
                        </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>



  

app/views/administrador/users/index.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
          </div>
          <div class="clearfix"></div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2><%= current_user.name%></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <br/>
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <%if current_user.admin? %>
              <h3>Painel Administrador</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to admin_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to administrador_users_path do %>
                      <i class="glyphicon glyphicon-user"></i>  Gestão de Usuários
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização de Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to devices_path do %>
                      <i class="glyphicon glyphicon-phone"></i> Gestão de Dispositivos 
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-ok"></i> Gestão da API
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sms_messages_path do %>
                      <i class="glyphicon glyphicon-envelope"></i> Configuração de Mensagens
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%else%>
              <h3>Painel Usuário</h3>
              <ul class="nav side-menu">
                  <li>
                    <%= link_to user_index_path do %>
                      <i class="glyphicon glyphicon-home"></i> Home
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sellers_path do %>
                      <i class="glyphicon glyphicon-tag"> </i> Gestão de Vendedores
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to status_path do %>
                      <i class="glyphicon glyphicon-eye-open"> </i> Vizualização dos Meus Dispositivos
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to dose_prices_path do %>
                      <i class="glyphicon glyphicon-usd"></i> Configuração de Preço
                      <span class="fa fa-chevron-down"></span>
                    <% end %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
          <!-- /sidebar menu -->
          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name%> <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <p>
                    Editar<span class="glyphicon glyphicon-edit"></span>
                  </p>
                <% end %> 
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
                  <p>
                    Sair <span class="glyphicon glyphicon-log-out"></span>
                  </p>
                <% end %>                
              </div> 
            </li>
          </ul>
        </div>
      </nav>
      <!-- /Navbar -->
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top tiles -->
    
        <!-- /top tiles -->
        <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="dashboard_graph">
            <div class="row x_title">
              <div class="col-md-6">
                <h3>Gerenciamento de Usuários</h3>
              </div>
              <div class="col-md-6">
                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                  <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                  <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                </div>
              </div>
              <!-- /Inicio Tabela -->
              <div class="col-lg-9">
                <div class="container">
                  <div class="row justify-content-center">
                    <div class="col-md-8">
                      <div class="table-responsive">
                        <table class="table">
                          <thead>
                            <tr>
                              <th>Nome</th>
                              <th>Email</th>
                              <th> </th>
                              <th>Editar</th>
                              <th>Excluir</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @users.each do |user| %>
                              <tr>
                                <td><%= user.name %></td>
                                <td><%= user.email %></td>
                                <td>
                                  <% if user.role == 'admin' %>
                                    <button type="button" class="btn btn-success">Administrador</button>
                                  <% else %>
                                    <button type="button" class="btn btn-primary">Usuário</button>
                                  <% end %>
                                </td>
                                <td>
                                  <%= button_to edit_administrador_user_path(user), method: :get, class: 'btn btn-warning' do %>
                                    <i class="glyphicon glyphicon-edit"></i>
                                  <% end %>
                                </td>
                                <td>
                                  <%= button_to administrador_user_path(user), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
                                    <i class="glyphicon glyphicon-trash"></i>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /FInal Tabela -->
            </div>
          </div>
        </div>
      </div>
      
        <br/>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>



  

app/views/user/show.html.erb
<h1>Detalhes do Usuário</h1>

    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Nome:</strong> <%= @user.name %></p>
    <!-- Adicione outras informações do usuário conforme necessário -->
    