config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      delete 'dissociate_seller', to: 'devices#dissociate_seller'
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'

  resources :api_manager

  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  


  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true



    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/models/device_seller.rb
class DeviceSeller < ApplicationRecord
  belongs_to :device
  belongs_to :seller
end

app/models/dose_price.rb
class DosePrice < ApplicationRecord
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    has_and_belongs_to_many :devices
end

app/models/sms_log.rb
class SmsLog < ApplicationRecord
   
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_one :sms_configuration

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { admin: 'admin', user: 'user'}
end

app/controllers/user_management_controller.rb
class UserManagementController < ApplicationController
  def index
    @users = User.all
    @sellers = Seller.all
    role = current_user.role
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_manager_helper.rb
module ApiManagerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devicelogs_helper.rb
module DevicelogsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/dose_prices_helper.rb
module DosePricesHelper
end

app/helpers/esp8266_helper.rb
module Esp8266Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_management_helper.rb
module UserManagementHelper
end

app/views/user_management/index.html.erb
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css">

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Painel Administrativo', admin_index_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opções <i class="fa fa-gear"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#"><%= current_user.name %></a>
            <%= link_to 'Editar', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div> 
        </li>
      </ul>
    </div>
  </nav>
  <!-- /Navbar -->

<div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <div class="col-lg-3">
            <div class="sidebar bg-dark">
                <ul class="list-group">
                <li class="list-group-item active">Dashboard</li>
                <li class="list-group-item"><%= link_to 'Home', admin_index_path %></li>
                <li class="list-group-item"><%= link_to 'Gestão de Usuários', administrador_users_path %></li>
                <li class="list-group-item"><%= link_to 'Gestão de Vendedores', sellers_path %></li>
                <li class="list-group-item"><%= link_to 'Vizualização de Dispositivos', status_path %></li>
                <li class="list-group-item"><%= link_to 'Gestão de Dispositivos', devices_path %></li>
                <li class="list-group-item"><%= link_to 'Gestão da API', sms_messages_path %></li>
                <li class="list-group-item"><%= link_to 'Configuração de Mensagens', sms_messages_path %></li>
                <li class="list-group-item"><%= link_to 'Configuração de Preço', dose_prices_path %></li>
            </div>
      </div>
      <!-- /Sidebar -->
        <div class="col-lg-9">
          <h1 class="mt-4">Meus Dispositivos</h1>
          <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <h1>Gerenciamento de Usuários</h1>
              <table class="table">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th> </th>
                    <th>Editar</th>
                    <th>Excluir</th>
                  </tr>
                </thead>
                <tbody>
                <% @users.each do |user| %>
                    <tr>
                      <td><%= user.name %></td>
                      <td><%= user.email %></td>
                      <td>
                          <% if user.role == 'admin' %>
                              <button type="button" class="btn btn-success">Administrador</button>
                          <% else %>
                              <button type="button" class="btn btn-primary">Usuário</button>
                          <% end %>
                      </td>
                      <td> 
                          <%= button_to edit_user_registration_path(user), method: :get, class: 'btn btn-warning' do %>
                          <i class="fa fa-edit"></i>
                          <% end %>
                      </td>
                    
                      <td> 
                          <%= button_to user_path(user), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
                          <i class="fa fa-trash"></i>
                          <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>      
    </div>
</div>
<%= render partial: 'layouts/footer-admin' %>